### ISSUE TITLE
typo in RegEx example

### ISSUE THREAD

**Issue by galantra** [pyxelr/My_Anki_Decks_of_Flashcards#1]
Hi,

I love your RegEx deck and left a review.

I think there's a typo in one of the examples:

`everything \\w is ^ literal`

should be:

`everything \w is ^ literal`

Shouldn't it?

**Comment by pyxelr** [comment]
Hi,
Thanks for spotting this error and notifying me! I've just updated the deck on AnkiWeb repository.
 
You're right; this is a typo that I copied straight from the quick reference of [Regex101](https://regex101.com/), and as I see, other users already [pointed out other issues](https://github.com/firasdib/Regex101/issues) with their quick reference entries. I'll try to keep my deck updated as they make any other changes.
