### ISSUE TITLE
missing highlighting in "word boundary" example

### ISSUE THREAD

**Issue by galantra** [pyxelr/My_Anki_Decks_of_Flashcards#2]
Hi, I think I found another error.

```
A word boundary
\b
Matches, without consuming any characters, immediately between a character matched by \w and a character not matched by \w (in either order). It cannot be used to separate non words from words. 


/d\b/g

word boundaries are odd
```
Sorry, I can't reproduce the highlighting on github.

But shouldn't w, d, s, a, e, o, d be the highlighted characters?

**Comment by galantra** [comment]
I believe the highlighting in this example is off, too_

```
A non-word boundary
\B
Matches, without consuming any characters, at the position between two characters matched by \w. 


/r\B/g

regex is really cool
```

Apart from those few issues, I'm making good progress on the deck. RegEx is a real time-saver and fun to figure out. So, really cool.

**Comment by pyxelr** [comment]
@galantra:
In both cases I didn't find any error.
I even verified these examples with [regex101.com](https://regex101.com/), and the results matched Anki flaschards. If you don't trust this web app, you can also try [RegExr](https://regexr.com/).

**1st proof (a word boundary)**:

![1 - Word boundary](https://user-images.githubusercontent.com/30161753/71935412-02882e00-31a7-11ea-9066-04c1f870db10.png)
`w, d, s, a, e, o, d` shouldn't be highlighted as you're only focusing on the character `d`.

**2nd proof (a non-word boundary)**:

![2 - Non-word boundary](https://user-images.githubusercontent.com/30161753/71935416-04ea8800-31a7-11ea-9e2b-63118c91dc2a.png)

Anyway, I am glad you're taking a great advantage of this deck!
